In [1]:
import numpy as np 
import pandas as pd     

import warnings         
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("dataset/clean-train.csv")

In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

cat_cols = ['Fuel', 'Transmission', 'Owner']

encoder = OneHotEncoder(sparse_output=False)
encoded_cols = encoder.fit_transform(df[cat_cols])

encoded_df = pd.DataFrame(encoded_cols, columns=encoder.get_feature_names_out(cat_cols))

dfe = pd.concat([df.drop(cat_cols, axis=1), encoded_df], axis=1)

dfe = dfe.dropna()

dfe.head()

,Car,Location,ODO,Year,Age,Mileage,Engine,Power,Seats,CP,SP,Fuel_Diesel,Fuel_Petrol,Transmission_Automatic,Transmission_Manual,Owner_First,Owner_Fourth & Above,Owner_Second,Owner_Third
0,Hyundai Creta 1.6 CRDi SX Option,Pune,41000,2015,8,19.670,1582.0,126.20,5.0,0.00,12.50,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
1,Honda Jazz V,Chennai,46000,2011,12,15.625,1199.0,88.70,5.0,8.61,4.50,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
2,Maruti Ertiga VDI,Chennai,87000,2012,11,20.770,1248.0,88.76,7.0,0.00,6.00,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
3,Audi A4 New 2.0 TDI Multitronic,Coimbatore,40670,2013,10,15.200,1968.0,140.80,5.0,0.00,17.74,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,Nissan Micra Diesel XV,Jaipur,86999,2013,10,23.080,1461.0,63.10,5.0,0.00,3.50,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [4]:
dfe.to_csv('dataset/encoded-train.csv', index=False)